---
- hosts: localhost
  become: yes
  tasks:
    - command:  curl -v -F r=releases -F hasPom=true -F e=ear -F file=@pom.xml -F file=@project-1.0.ear -u Pace_Nexus_user:joy.cot-16 https://repo1-itg.core.hpecorp.net/nexus/content/repositories/HPINT-release1-M2/com/hpe/test1/11/project-1.0.ear
