- hosts: localhost
  become: yes
  tasks:
    - name: Upload to nexus
       uri:
         url:  http://localhost:8081/nexus/content/repositories/test1/com/hpe/pace/test/{{ commitid }}/{{ item }}
         user: admin
         password: admin123
         method: PUT
         status_code: 201, 200
         src: /home/gayathri/ansible/{{ item }}
      with_items:
        - helloworld.ear
        - test.ear
